server:
  port: 28080

spring:
  thymeleaf:
    mode: HTML5

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    #url: jdbc:mysql:aurora://mytodo.c9xxxxxxx.ap-northeast-1.rds.amazonaws.com:3306/db_test
    url: jdbc:mysql://localhost:3306/db_test
    username: root


mybatis:
  configuration:
    useColumnLabel: true
    mapUnderscoreToCamelCase: true
  mapper-locations: mybatis/sql/*.xml

